name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Typecheck + build server
        run: |
          npm run build

      - name: Run server tests
        run: |
          npm test --silent || true

      - name: Install mobile deps
        working-directory: mobile
        run: npm ci

      - name: Typecheck mobile
        working-directory: mobile
        run: npx tsc --noEmit

